<?php
/**
 * Created by IntelliJ IDEA.
 * User: yux
 * Date: 30/12/17
 * Time: 12.56
 */

namespace cms\controller;


use cms\library\crud\Response;
use Doctrine\DBAL\Exception\InvalidArgumentException;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;
use Doctrine\ORM\OptimisticLockException;
use yuxblank\phackp\http\api\ServerRequestInterface;

class MenuController extends BaseMenuController
{
    public function create(ServerRequestInterface $serverRequest)
    {
        try {
            $result = parent::create($serverRequest);
        } catch (OptimisticLockException $e) {

        } catch (InvalidArgumentException $e) {

        }

        return Response::ok($result->offsetGet('menu'))->build();
    }

    public function read(ServerRequestInterface $serverRequest)
    {
        try {
            $result  = parent::read($serverRequest);
            return Response::ok(($result->offsetGet('menu') ?: $result->offsetGet('menu.list')))->build();
        } catch (NoResultException $e) {
        } catch (NonUniqueResultException $e) {
        } // TODO: Change the autogenerated stub
    }

    public function update(ServerRequestInterface $serverRequest)
    {
        parent::update($serverRequest); // TODO: Change the autogenerated stub
    }

    public function delete(ServerRequestInterface $serverRequest)
    {
        parent::delete($serverRequest); // TODO: Change the autogenerated stub
    }


}