POST {{host}}/admin/content
Content-Type: application/json
Authorization: {{token}}
Cookie: {{xdebug}}

{"title":"Test","content":"<p>Test</p>\n","categories":[{"id": 1,"title":"TEST1","content":"This is my textarea to be replaced with CKEditor.\r\n","date_created":null,"date_updated":null,"meta_tags":"","alias":"test1"}],"status":0,"meta_description":"test","meta_tags":"test1"}

###

PUT {{host}}/admin/content
Content-Type: application/json
Authorization: {{token}}
Cookie: {{xdebug}}

{"title":"Test","content":"<p>Test</p>\n","categories":[{"id": 1,"title":"TEST1","content":"This is my textarea to be replaced with CKEditor.\r\n","date_created":null,"date_updated":null,"meta_tags":"","alias":"test1"}],"status":0,"meta_description":"test","meta_tags":"test1"}

###
PUT {{host}}/admin/content
Content-Type: application/json
Authorization: {{token}}
Cookie: {{xdebug}}

{"id":2,"title":"Test 2","content":"<p>Test</p>\n","meta_tags":"test1","meta_title":"Test","alias":"test"}

###

PUT {{host}}/admin/content
Content-Type: application/json
Authorization: {{token}}
Cookie: {{xdebug}}

{"id":70,"title":"LAST","content":"","meta_tags":"","meta_title":"","alias":"","categories":[{"id":1,"title":"TEST1MERGE","content":"<p>This is my textarea to be replaced with CKEditor.</p>\n","meta_tags":"","meta_title":null,"alias":"test1","status":1}],"status":0}


###

GET {{host}}/admin/categories?active=1
Content-Type: application/json
Authorization: {{token}}
Cookie: {{xdebug}}


###